<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invoices.Common\Invoices.Common.csproj" />
    <ProjectReference Include="..\Invoices.Data\Invoices.Data.csproj" />
    <ProjectReference Include="..\Lib\Lib.csproj" />
  </ItemGroup>

</Project>
